spp-platform:
  host: ${SPP_PLATFORM_HOST:-0.0.0.0}
  port: ${SPP_PLATFORM_PORT:-5445}
  access_token: ${SPP_SYSTEM_ACCESS_TOKEN:-change-me}
  logging:
    level: ${SPP_LOGGING_LEVEL:-trace}
  probe:
    bridge_port: ${SPP_PROBE_BRIDGE_PORT:-5450}
  marker:
    bridge_port: ${SPP_MARKER_BRIDGE_PORT:-5455}
  processor:
    bridge_port: ${SPP_PROCESSOR_BRIDGE_PORT:-5460}

storage:
  selector: ${SPP_STORAGE:-memory}

skywalking-oap:
  host: ${SPP_OAP_HOST:-skywalking-oap}
  port: ${SPP_OAP_PORT:-12800}
